name: sass_extract
description: A tool to extract Sass variables from a file
version: 1.0.0

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  charcode: ^1.3.1
  collection: ^1.17.2
  js: ^0.6.7
  node_interop: ^2.1.0
  path: ^1.8.3
  sass: ^1.64.0
  source_span: ^1.10.0
  stack_trace: ^1.11.1
  tuple: ^2.0.2

dev_dependencies:
  analyzer: ^5.13.0
  cli_pkg: ^2.4.7
  crypto: ^3.0.0
  dart_style: ^2.0.0
  grinder: ^0.9.4
  lints: ^2.0.0
  test: ^1.24.4
  test_descriptor: ^2.0.1
