name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Create Github release
        run: dart run grinder pkg-github-all
      - name: Fix Github release permissions
        run: dart run grinder pkg-github-fix-permissions
      - name: Release
        run: dart run grinder pkg-npm-deploy
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
